Feature: T1.5 Threat
  Background:
    Given a deterministic encounter with critChance 0
    And threat multipliers and switching thresholds come from data definitions

  Scenario Outline: C1 Switching requires strictly exceeding the challenger distance threshold
    Given the current target has 100 threat
    And a challenger has <threat> threat at <distance> meters from the enemy body
    When all players have finished their tick actions
    Then the enemy target is <target>
    Examples:
      | distance | threat | target     |
      | 4        | 105    | current    |
      | 4        | 110    | current    |
      | 4        | 111    | challenger |
      | 4.0001   | 125    | current    |
      | 4.0001   | 130    | current    |
      | 4.0001   | 131    | challenger |

  Scenario: C2 Taunt forces its target for exactly 60 ticks
    Given the maximum threat in the enemy table is 100
    When the Jaguar resolves Taunt
    Then its threat becomes max(its own threat, the table maximum times 11000 divided by 10000)
    And the enemy immediately targets the Jaguar with 60 forced ticks remaining
    And the maximum includes the Jaguar's existing entry
    When another player exceeds the normal switching threshold
    Then the Jaguar remains the target through the next 59 ticks
    And on the next tick the force expires and normal selection uses the Jaguar as the current target

  Scenario: C3 Effective healing is shared between enemies alive when healing resolves
    Given three living enemies and one dead enemy
    And an ally is missing 1 health
    When Remedy heals that ally for 120
    Then each living enemy gains 0.5 divided by 3 threat toward the healer
    And the dead enemy's table is unchanged
    And no threat is generated by the 119 overhealing
    And healing a full health ally generates no threat

  Scenario: C4 Roar adds flat threat without the Jaguar multiplier
    Given living enemies inside, at the boundary and outside Roar's area
    When the Jaguar resolves Roar
    Then each hit enemy receives 25 damage and 125 threat toward the Jaguar
    And the 125 threat consists of 25 times 3 plus 50
    And dead enemies and enemies outside the area gain no threat

  Scenario: Damage uses final damage and the source class multiplier
    When a player's damage event resolves against an enemy
    Then only that enemy's table gains final damage times the source class multiplier
    And existing threat accumulates without mutating the original table
    And the killing hit also generates its final damage threat

  Scenario: Selection uses living threat entries and stable id ordering
    Given an enemy with no current target or with a dead current target
    When targets are reevaluated
    Then the living player with the greatest threat in that table becomes its target immediately
    And equal threat is resolved by the lowest string id regardless of insertion order
    And an empty table with no current target keeps a null target
    And dead players cannot generate threat or remain forced targets

  Scenario: Threat follows the existing tick order and preserves references
    When a tick advances
    Then existing forced-target timers decrease before completed casts and player inputs
    And threat is applied immediately with each damage or healing event
    And after all players' target, last move and first cast actions enemy targets are reevaluated once
    And unchanged entities and threat tables retain their references
    And frozen input state remains unchanged and replay produces identical results
    And threat accumulates while pull remains unimplemented for T1.7
    And no enemy movement, enemy auto attacks or xolo spawning occurs
